language: ruby
rvm:
  - 1.9.3
bundler_args: --without development
gemfile:
  - Gemfile
branches:
  only:
    - master
before_script:
  - psql -c 'create database reader_test;' -U postgres
  - bundle exec rake db:migrate
env:
  - DB_USER=postgres
script: "rake --trace"
