#
# This file configures the New Relic Agent.  New Relic monitors
# Ruby, Java, .NET, PHP, and Python applications with deep visibility and low overhead.
# For more information, visit www.newrelic.com.
#
# Generated August 03, 2011
#
# This configuration file is custom generated for WellnessFX

# Here are the settings that are common to all environments:
development: &default_settings
  # ============================== LICENSE KEY ===============================

  # Developer mode should be off in every environment but
  # development as it has very high overhead in memory.
  developer_mode: true

